 CREATE DATABASE MAIN_DB CHARSET=UTF8;
 USE MAIN_DB;
 CREATE TABLE USER(
	ID VARCHAR(10) NOT NULL UNIQUE,
	NAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(12) NOT NULL,
	PHONE_NUMBER VARCHAR(11) NOT NULL,
	ADDRESS TEXT,
	BIRTHDAY DATE NOT NULL,
	TYPE ENUM('ADMINISTRATOR', 'SUBMITTER', 'EVALUATOR') NOT NULL,
	SCORE FLOAT DEFAULT 0, CONSTRAINT VALID_SCORE CHECK((SCORE >= 0 AND SCORE <= 10)),
	PRIMARY KEY(ID));

CREATE TABLE TASK(
	NAME VARCHAR(200) NOT NULL UNIQUE,
	DESCRIPTION TEXT NOT NULL,
	START_PERIOD DATE NOT NULL,
	END_PERIOD DATE NOT NULL,
	MIN_SUBMIT_PERIOD INT NOT NULL,
	STANDARD_OF_PASS INT, CONSTRAINT VALID_STANDARD_OF_PASS CHECK((STANDARD_OF_PASS >= 0 AND STANDARD_OF_PASS <= 100)),
	DATA_TABLE_NAME TEXT NOT NULL UNIQUE,
	PRIMARY KEY(NAME));
	
CREATE TABLE MANAGE(
	MANAGER_ID VARCHAR(10) NOT NULL,
	TASK_NAME VARCHAR(200) NOT NULL,
	PRIMARY KEY(MANAGER_ID, TASK_NAME),
	FOREIGN KEY(MANAGER_ID) REFERENCES USER(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(TASK_NAME) REFERENCES TASK(NAME)
		ON DELETE CASCADE
		ON UPDATE CASCADE);

CREATE TABLE PARTICIPATE(
	PARTICIPANT_ID VARCHAR(10) NOT NULL,
	TASK_NAME VARCHAR(200) NOT NULL,
	PRIMARY KEY(PARTICIPANT_ID, TASK_NAME),
	FOREIGN KEY(PARTICIPANT_ID) REFERENCES USER(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(TASK_NAME) REFERENCES TASK(NAME)
		ON DELETE CASCADE
		ON UPDATE CASCADE);

CREATE TABLE APPLY(
	APPLICANT_ID VARCHAR(10) NOT NULL,
	TASK_NAME VARCHAR(200) NOT NULL,
	PRIMARY KEY(APPLICANT_ID, TASK_NAME),
	FOREIGN KEY(APPLICANT_ID) REFERENCES USER(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(TASK_NAME) REFERENCES TASK(NAME)
		ON DELETE CASCADE
		ON UPDATE CASCADE);

CREATE TABLE SOURCE_DATA_TYPE(
	TASK_NAME VARCHAR(200) NOT NULL,
	TABLE_NAME VARCHAR(200) NOT NULL,
	SCHEMA_INFO TEXT NOT NULL,
	PRIMARY KEY(TASK_NAME, TABLE_NAME),
	FOREIGN KEY(TASK_NAME) REFERENCES TASK(NAME)
		ON DELETE CASCADE
		ON UPDATE CASCADE);

CREATE TABLE FILE(
	ID VARCHAR(50) NOT NULL,
	NUMBER INT,
	START_PERIOD DATE,
	END_PERIOD DATE,
	TYPE ENUM('CSV', 'TAB'),
	TABLE_NAME TEXT NOT NULL,
	PRIMARY KEY(ID));

CREATE TABLE SUBMIT(
	SUBMITTER_ID VARCHAR(10) NOT NULL,
	FILE_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY(SUBMITTER_ID, FILE_ID),
	FOREIGN KEY(SUBMITTER_ID) REFERENCES USER(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	FOREIGN KEY(FILE_ID) REFERENCES FILE(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE);

CREATE TABLE PARSING_DATA_SEQUENCE_FILE(
	FILE_ID VARCHAR(50) NOT NULL,
	TYPE ENUM('CSV') NOT NULL,
	P_NP ENUM('EMPTY', 'PASS', 'NONPASS') DEFAULT 'EMPTY',
	SCORE INT, CONSTRAINT VALID_SCORE CHECK((SCORE >= 0 AND SCORE <= 10)),
	DUPLICATED_TUPLE_NUMBER INT NOT NULL,
	SUBMIT_TIME DATE NOT NULL,
	ALL_TUPLE_NUMBER INT NOT NULL,
	EVALUATOR_ID VARCHAR(10) NOT NULL,
	PRIMARY KEY(FILE_ID),
	FOREIGN KEY(EVALUATOR_ID) REFERENCES USER(ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE);

CREATE TABLE TESTTASK(ATTR1 INT, ATTR2 TEXT, ATTR3 FLOAT);
CREATE TABLE TESTDATA1(FILE_ID VARCHAR(50), SUBATTR1 INT, SUBATTR2 TEXT, SUBATTR3 FLOAT);
CREATE TABLE TESTDATA2(FILE_ID VARCHAR(50), SUBATTR4 INT, SUBATTR5 TEXT, SUBATTR6 FLOAT);
CREATE TABLE TESTDATA3(FILE_ID VARCHAR(50), SUBATTR7 INT, SUBATTR8 TEXT, SUBATTR9 FLOAT);
INSERT INTO TASK VALUES('Test Task', 'This the description of test task.', '2020-09-01', '2020-12-31', 5, 8, 'TESTTASK');
INSERT INTO SOURCE_DATA_TYPE VALUES('Test Task', 'TESTDATA1', '{"SUBATTR1":"ATTR1", "SUBATTR2":"ATTR2", "SUBATTR3":"ATTR3"}');
INSERT INTO SOURCE_DATA_TYPE VALUES('Test Task', 'TESTDATA2', '{"SUBATTR4":"ATTR1", "SUBATTR5":"ATTR2", "SUBATTR6":"ATTR3"}');
INSERT INTO SOURCE_DATA_TYPE VALUES('Test Task', 'TESTDATA3', '{"SUBATTR7":"ATTR1", "SUBATTR8":"ATTR2", "SUBATTR9":"ATTR3"}');
INSERT INTO FILE VALUES('test_file1', 3, '2020-09-01', '2020-10-01', 'CSV', 'TESTDATA1');
INSERT INTO FILE VALUES('test_file2', 5, '2020-10-01', '2020-11-01', 'CSV', 'TESTDATA2');
INSERT INTO FILE VALUES('test_file3', 2, '2020-11-01', '2020-12-01', 'CSV', 'TESTDATA3');
INSERT INTO SUBMIT VALUES('submit1', 'test_file1');
INSERT INTO SUBMIT VALUES('submit2', 'test_file2');
INSERT INTO SUBMIT VALUES('submit3', 'test_file3');
INSERT INTO TESTDATA1 VALUES(0, 'A', NULL);
INSERT INTO TESTDATA2 VALUES(1, NULL, 1.5);
INSERT INTO TESTDATA3 VALUES(NULL, 'A', 0.5);
INSERT INTO PARSING_DATA_SEQUENCE_FILE VALUES('e

CREATE TABLE TEST_TASK(
	ATTR1 TEXT NOT 
/*
INSERT INTO USER(id, name, password, phone_number, birthday, type)
VALUES('admin', '관리자', 'admin', '01029876311', '1996-07-02', 'ADMINISTRATOR');
VALUES('eval1', '평가자1', 'eval1', '01011111111', '1996-01-01', 'EVALUATOR'),
VALUES('eval2', '평가자2', 'eval2', '01011111111', '1996-02-02', 'EVALUATOR'),
VALUES('eval3', '평가자3', 'eval3', '01011111111', '1996-03-03', 'EVALUATOR'),
VALUES('submit1', '제출자1', 'submit1', '01011111111', '1996-01-01', 'SUBMITTER'),
VALUES('submit2', '제출자2', 'submit2', '01011111111', '1996-02-02', 'SUBMITTER'),
VALUES('submit3', '제출자3', 'submit3', '01011111111', '1996-03-03', 'SUBMITTER');*/